/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/sections/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "text-green-program",
    "text-orange-design",
    "text-violet-design",
    "text-blue-marketing",
    "bg-green-program",
    "bg-orange-design",
    "bg-violet-design",
    "bg-blue-marketing",
    "border-green-program",
    "border-orange-design",
    "border-violet-design",
    "border-blue-marketing",
  ],
  mode: "jit",
  theme: {
    extend: {
      colors: {
        "primary-0": "var(--primary-0)",
        "primary-10": "var(--primary-10)",
        "primary-20": "var(--primary-20)",
        "primary-30": "var(--primary-30)",
        "primary-40": "var(--primary-40)",
        "primary-50": "var(--primary-50)",
        "primary-60": "var(--primary-60)",
        "primary-70": "var(--primary-70)",
        "primary-80": "var(--primary-80)",
        "primary-90": "var(--primary-90)",
        "primary-95": "var(--primary-95)",
        "primary-99": "var(--primary-99)",
        "primary-100": "var(--primary-100)",
        "secondary-0": "var(--secondary-0)",
        "secondary-10": "var(--secondary-10)",
        "secondary-20": "var(--secondary-20)",
        "secondary-30": "var(--secondary-30)",
        "secondary-40": "var(--secondary-40)",
        "secondary-50": "var(--secondary-50)",
        "secondary-60": "var(--secondary-60)",
        "secondary-70": "var(--secondary-70)",
        "secondary-80": "var(--secondary-80)",
        "secondary-90": "var(--secondary-90)",
        "secondary-95": "var(--secondary-95)",
        "tertiary-10": "var(--tertiary-10)",
        "tertiary-20": "var(--tertiary-20)",
        "tertiary-30": "var(--tertiary-30)",
        "tertiary-40": "var(--tertiary-40)",
        "tertiary-50": "var(--tertiary-50)",
        "tertiary-60": "var(--tertiary-60)",
        "tertiary-70": "var(--tertiary-70)",
        "tertiary-80": "var(--tertiary-80)",
        "tertiary-90": "var(--tertiary-90)",
        "tertiary-95": "var(--tertiary-95)",
        "error-10": "var(--error-10)",
        "error-20": "var(--error-20)",
        "error-30": "var(--error-30)",
        "error-40": "var(--error-40)",
        "error-50": "var(--error-50)",
        "error-60": "var(--error-60)",
        "error-70": "var(--error-70)",
        "error-80": "var(--error-80)",
        "error-90": "var(--error-90)",
        "error-95": "var(--error-95)",
        "neutral-10": "var(--neutral-10)",
        "neutral-20": "var(--neutral-20)",
        "neutral-30": "var(--neutral-30)",
        "neutral-40": "var(--neutral-40)",
        "neutral-50": "var(--neutral-50)",
        "neutral-60": "var(--neutral-60)",
        "neutral-70": "var(--neutral-70)",
        "neutral-80": "var(--neutral-80)",
        "neutral-90": "var(--neutral-90)",
        "neutral-95": "var(--neutral-95)",
        "gold": "var(--gold)",
        "green-program": "var(--green-program)",
        "orange-design": "var(--orange-design)",
        "violet-design": "var(--violet-design)",
        "blue-marketing": "var(--blue-marketing)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        "display-large": "var(--font-display-large)",
        "display-medium": "var(--font-display-medium)",
        "display-small": "var(--font-display-small)",
        "headline-large": "var(--font-headline-large)",
        "headline-medium": "var(--font-headline-medium)",
        "headline-small": "var(--font-headline-small)",
        "title-large": "var(--font-title-large)",
        "title-medium": "var(--font-title-medium)",
        "title-small": "var(--font-title-small)",
        "label-large": "var(--font-label-large)",
        "label-medium": "var(--font-label-medium)",
        "label-small": "var(--font-label-small)",
        "body-large": "var(--font-body-large)",
        "body-medium": "var(--font-body-medium)",
        "body-small": "var(--font-body-small)",
      },
      fontSize: {
        "display-large": [
          "var(--display-large-font-size)",
          {
            lineHeight: "var(--display-large-line-height)",
            letterSpacing: "var(--display-large-letter-spacing)",
          },
        ],
        "display-medium": [
          "var(--display-medium-font-size)",
          {
            lineHeight: "var(--display-medium-line-height)",
            letterSpacing: "var(--display-medium-letter-spacing)",
          },
        ],
        "display-small": [
          "var(--display-small-font-size)",
          {
            lineHeight: "var(--display-small-line-height)",
            letterSpacing: "var(--display-small-letter-spacing)",
          },
        ],
        "headline-large": [
          "var(--headline-large-font-size)",
          {
            lineHeight: "var(--headline-large-line-height)",
            letterSpacing: "var(--headline-large-letter-spacing)",
          },
        ],
        "headline-medium": [
          "var(--headline-medium-font-size)",
          {
            lineHeight: "var(--headline-medium-line-height)",
            letterSpacing: "var(--headline-medium-letter-spacing)",
          },
        ],
        "headline-small": [
          "var(--headline-small-font-size)",
          {
            lineHeight: "var(--headline-small-line-height)",
            letterSpacing: "var(--headline-small-letter-spacing)",
          },
        ],
        "title-large": [
          "var(--title-large-font-size)",
          {
            lineHeight: "var(--title-large-line-height)",
            letterSpacing: "var(--title-large-letter-spacing)",
          },
        ],
        "title-small": [
          "var(--title-small-font-size)",
          {
            lineHeight: "var(--title-small-line-height)",
            letterSpacing: "var(--title-small-letter-spacing)",
          },
        ],
        "label-large": [
          "var(--label-large-font-size)",
          {
            lineHeight: "var(--label-large-line-height)",
            letterSpacing: "var(--label-large-letter-spacing)",
          },
        ],
        "label-medium": [
          "var(--label-medium-font-size)",
          {
            lineHeight: "var(--label-medium-line-height)",
            letterSpacing: "var(--label-medium-letter-spacing)",
          },
        ],
        "label-small": [
          "var(--label-small-font-size)",
          {
            lineHeight: "var(--label-small-line-height)",
            letterSpacing: "var(--label-small-letter-spacing)",
          },
        ],
        "body-large": [
          "var(--body-large-font-size)",
          {
            lineHeight: "var(--body-large-line-height)",
            letterSpacing: "var(--body-large-letter-spacing)",
          },
        ],
        "body-medium": [
          "var(--body-medium-font-size)",
          {
            lineHeight: "var(--body-medium-line-height)",
            letterSpacing: "var(--body-medium-letter-spacing)",
          },
        ],
        "body-small": [
          "var(--body-small-font-size)",
          {
            lineHeight: "var(--body-small-line-height)",
            letterSpacing: "var(--body-small-letter-spacing)",
          },
        ],
      },
    },
  },
  plugins: [],
};
